[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/NXWorkshopPlugin"]

[project]
name = "simplnx.NXWorkshopPlugin"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
  "numpy"
]

[project.entry-points."simplnx.plugins"]
plugin = "NXWorkshopPlugin"